# -*- coding: utf-8 -*-
"""Untitled38.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bg_p5zQ73fLyp4RqfscPHpaCqUF9r1vO
"""

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import time

from tensorflow.keras import layers, models
from tensorflow.keras.applications import MobileNetV2

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

print("TensorFlow version:", tf.__version__)

import tensorflow as tf

# Load CIFAR-10
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.cifar10.load_data()

print("Training data shape:", x_train.shape)
print("Training labels shape:", y_train.shape)

print("Testing data shape:", x_test.shape)
print("Testing labels shape:", y_test.shape)

# Convert pixel values from [0,255] to [0,1]
x_train = x_train.astype("float32") / 255.0
x_test = x_test.astype("float32") / 255.0

# Convert labels to 1D
y_train = y_train.flatten()
y_test = y_test.flatten()

print("Minimum pixel value:", x_train.min())
print("Maximum pixel value:", x_train.max())

class_names = [
    "Airplane",
    "Automobile",
    "Bird",
    "Cat",
    "Deer",
    "Dog",
    "Frog",
    "Horse",
    "Ship",
    "Truck"
]

print(class_names)

plt.figure(figsize=(15, 6))

for i in range(10):
    plt.subplot(2, 5, i + 1)
    plt.imshow(x_train[i])
    plt.title(class_names[y_train[i]])
    plt.axis("off")

plt.suptitle("Sample CIFAR-10 Images")
plt.tight_layout()
plt.show()

x_train, x_val, y_train, y_val = train_test_split(
    x_train,
    y_train,
    test_size=0.1,
    random_state=42,
    stratify=y_train
)

print("Training set:", x_train.shape)
print("Validation set:", x_val.shape)
print("Testing set:", x_test.shape)

# Load MobileNetV2 pretrained on ImageNet
base_model = MobileNetV2(
    weights="imagenet",
    include_top=False,
    input_shape=(96, 96, 3)
)

# Freeze the convolutional base
base_model.trainable = False

# Build model
model = models.Sequential([

    # CIFAR-10 images are 32x32, so resize them
    layers.Input(shape=(32, 32, 3)),
    layers.Resizing(96, 96),

    # MobileNetV2 expects approximately [-1, 1]
    layers.Rescaling(2.0, offset=-1.0),

    base_model,

    layers.GlobalAveragePooling2D(),

    layers.Dense(128, activation="relu"),

    layers.Dense(10, activation="softmax")
])

model.summary()

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

print("Model compiled successfully.")

import tensorflow as tf

# Recompile the model to ensure it's in a compiled state if not already
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

start_time = time.time()

history = model.fit(
    x_train,
    y_train,
    validation_data=(x_val, y_val),
    epochs=10,
    batch_size=32,
    verbose=1
)

training_time = time.time() - start_time

print("\nTraining time:", round(training_time, 2), "seconds")
print("Training time:", round(training_time / 60, 2), "minutes")

plt.figure(figsize=(8, 5))

plt.plot(history.history["accuracy"], label="Training Accuracy")
plt.plot(history.history["val_accuracy"], label="Validation Accuracy")

plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.title("Training Accuracy vs Validation Accuracy")
plt.legend()
plt.grid(True)

plt.show()

plt.figure(figsize=(8, 5))

plt.plot(history.history["loss"], label="Training Loss")
plt.plot(history.history["val_loss"], label="Validation Loss")

plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training Loss vs Validation Loss")
plt.legend()
plt.grid(True)

plt.show()

test_loss, test_accuracy = model.evaluate(
    x_test,
    y_test,
    batch_size=32,
    verbose=1
)

print("Test Loss:", test_loss)
print("Test Accuracy:", test_accuracy)
print("Test Accuracy (%):", test_accuracy * 100)

# Allow the base model to be trainable
base_model.trainable = True

# Freeze most layers and unfreeze the last 30 layers
for layer in base_model.layers[:-30]:
    layer.trainable = False

for layer in base_model.layers[-30:]:
    layer.trainable = True

# Recompile with a smaller learning rate
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

print("Trainable layers after fine-tuning:")

for layer in base_model.layers[-10:]:
    print(layer.name, layer.trainable)

# ============================================================
# FINE-TUNING - UNFREEZE THE LAST CONVOLUTIONAL BLOCK
# ============================================================

# First, make the base model trainable
base_model.trainable = True

# Freeze all layers initially
for layer in base_model.layers:
    layer.trainable = False

# Find the last convolutional block
# MobileNetV2 contains layers such as block_16_project,
# block_16_depthwise, block_16_expand, etc.

unfreeze = False

for layer in base_model.layers:
    if layer.name.startswith("block_16"):
        unfreeze = True

    if unfreeze:
        layer.trainable = True

# Keep BatchNormalization layers frozen during fine-tuning
# This makes fine-tuning more stable on the relatively small CIFAR-10 images.
for layer in base_model.layers:
    if isinstance(layer, tf.keras.layers.BatchNormalization):
        layer.trainable = False

# Display which layers are trainable
print("========== FINE-TUNING LAYERS ==========")

for layer in base_model.layers:
    if layer.trainable:
        print(layer.name, "-> Trainable")

# Count trainable parameters
trainable_params = np.sum(
    [np.prod(v.shape) for v in model.trainable_weights]
)

print("\nTrainable parameters:", trainable_params)

# ============================================================
# RECOMPILE WITH SMALLER LEARNING RATE
# ============================================================

model.compile(
    optimizer=tf.keras.optimizers.Adam(
        learning_rate=0.0001
    ),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

print("\nModel recompiled for fine-tuning.")

# ============================================================
# FINE-TUNING TRAINING
# ============================================================

fine_tune_start = time.time()

fine_history = model.fit(
    x_train,
    y_train,
    validation_data=(x_val, y_val),
    epochs=5,
    batch_size=32,
    verbose=1
)

fine_tune_time = time.time() - fine_tune_start

print("\n========== FINE-TUNING RESULTS ==========")
print("Fine-tuning time:",
      round(fine_tune_time, 2), "seconds")
print("Fine-tuning time:",
      round(fine_tune_time / 60, 2), "minutes")

# ============================================================
# COMPARE BEFORE AND AFTER FINE-TUNING
# ============================================================

final_loss, final_accuracy = model.evaluate(
    x_test,
    y_test,
    batch_size=32,
    verbose=1
)

print("\n========== FINE-TUNING COMPARISON ==========")

print(
    "Accuracy BEFORE fine-tuning:",
    round(test_accuracy * 100, 2),
    "%"
)

print(
    "Accuracy AFTER fine-tuning:",
    round(final_accuracy * 100, 2),
    "%"
)

improvement = (final_accuracy - test_accuracy) * 100

print(
    "Improvement:",
    round(improvement, 2),
    "percentage points"
)

plt.figure(figsize=(8, 5))

plt.plot(
    fine_history.history["loss"],
    label="Fine-Tuning Training Loss"
)

plt.plot(
    fine_history.history["val_loss"],
    label="Fine-Tuning Validation Loss"
)

plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Fine-Tuning Loss")
plt.legend()
plt.grid(True)

plt.show()

# Evaluate final model
final_loss, final_accuracy = model.evaluate(
    x_test,
    y_test,
    batch_size=32,
    verbose=1
)

print("\n========== FINE-TUNING COMPARISON ==========")

print("Accuracy BEFORE fine-tuning:",
      round(test_accuracy * 100, 2), "%")

print("Accuracy AFTER fine-tuning:",
      round(final_accuracy * 100, 2), "%")

improvement = (final_accuracy - test_accuracy) * 100

print("Improvement:",
      round(improvement, 2), "percentage points")

y_prob = model.predict(
    x_test,
    batch_size=32,
    verbose=1
)

y_pred = np.argmax(y_prob, axis=1)

print("Predictions generated.")
print("Prediction shape:", y_pred.shape)

accuracy = accuracy_score(y_test, y_pred)

precision = precision_score(
    y_test,
    y_pred,
    average="weighted"
)

recall = recall_score(
    y_test,
    y_pred,
    average="weighted"
)

f1 = f1_score(
    y_test,
    y_pred,
    average="weighted"
)

print("========== PERFORMANCE METRICS ==========")

print("Accuracy :", round(accuracy, 4))
print("Precision:", round(precision, 4))
print("Recall   :", round(recall, 4))
print("F1-score :", round(f1, 4))

print("========== CLASSIFICATION REPORT ==========\n")

print(
    classification_report(
        y_test,
        y_pred,
        target_names=class_names
    )
)

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(10, 8))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=class_names,
    yticklabels=class_names
)

plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.title("Confusion Matrix")

plt.show()

misclassified = np.where(y_test != y_pred)[0]

plt.figure(figsize=(15, 8))

for i, index in enumerate(misclassified[:10]):

    plt.subplot(2, 5, i + 1)

    plt.imshow(x_test[index])

    plt.title(
        f"True: {class_names[y_test[index]]}\n"
        f"Pred: {class_names[y_pred[index]]}"
    )

    plt.axis("off")

plt.suptitle("Misclassified CIFAR-10 Images")
plt.tight_layout()
plt.show()

total_params = model.count_params()

print("Total Parameters:", total_params)

total_params = model.count_params()

print("\n========== FINAL RESULTS ==========")

print(f"Training Accuracy : {history.history['accuracy'][-1] * 100:.2f}%")
print(f"Testing Accuracy  : {accuracy * 100:.2f}%")
print(f"Precision         : {precision:.4f}")
print(f"Recall            : {recall:.4f}")
print(f"F1-score          : {f1:.4f}")
print(f"Initial Training Time : {training_time:.2f} seconds")
print(f"Fine-Tuning Time      : {fine_tune_time:.2f} seconds")
print(f"Total Parameters      : {total_params:,}")

def create_transfer_model(
    learning_rate=0.001,
    optimizer_name="Adam",
    dense_units=128
):

    base = MobileNetV2(
        weights="imagenet",
        include_top=False,
        input_shape=(96, 96, 3)
    )

    base.trainable = False

    model_temp = models.Sequential([
        layers.Input(shape=(32, 32, 3)),
        layers.Resizing(96, 96),
        layers.Rescaling(2.0, offset=-1.0),
        base,
        layers.GlobalAveragePooling2D(),
        layers.Dense(dense_units, activation="relu"),
        layers.Dense(10, activation="softmax")
    ])

    if optimizer_name == "Adam":
        optimizer = tf.keras.optimizers.Adam(
            learning_rate=learning_rate
        )
    else:
        optimizer = tf.keras.optimizers.SGD(
            learning_rate=learning_rate
        )

    model_temp.compile(
        optimizer=optimizer,
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"]
    )

    return model_temp

# ============================================================
# HYPERPARAMETER STUDY
# ============================================================

import pandas as pd
import gc

def create_hyperparameter_model(
    learning_rate=0.001,
    optimizer_name="Adam",
    dense_units=128,
    freeze_type="all"
):

    base = MobileNetV2(
        weights="imagenet",
        include_top=False,
        input_shape=(96, 96, 3)
    )

    # --------------------------------------------------------
    # Freeze configuration
    # --------------------------------------------------------

    if freeze_type == "all":

        base.trainable = False

    else:

        base.trainable = True

        # Freeze everything first
        for layer in base.layers:
            layer.trainable = False

        # Unfreeze last MobileNetV2 block
        unfreeze = False

        for layer in base.layers:

            if layer.name.startswith("block_16"):
                unfreeze = True

            if unfreeze:
                layer.trainable = True

        # Keep BatchNormalization frozen
        for layer in base.layers:
            if isinstance(
                layer,
                tf.keras.layers.BatchNormalization
            ):
                layer.trainable = False

    # --------------------------------------------------------
    # Build model
    # --------------------------------------------------------

    temp_model = models.Sequential([

        layers.Input(shape=(32, 32, 3)),

        layers.Resizing(96, 96),

        layers.Rescaling(
            2.0,
            offset=-1.0
        ),

        base,

        layers.GlobalAveragePooling2D(),

        layers.Dense(
            dense_units,
            activation="relu"
        ),

        layers.Dense(
            10,
            activation="softmax"
        )
    ])

    # --------------------------------------------------------
    # Optimizer
    # --------------------------------------------------------

    if optimizer_name == "Adam":

        optimizer = tf.keras.optimizers.Adam(
            learning_rate=learning_rate
        )

    else:

        optimizer = tf.keras.optimizers.SGD(
            learning_rate=learning_rate
        )

    # --------------------------------------------------------
    # Compile
    # --------------------------------------------------------

    temp_model.compile(
        optimizer=optimizer,
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"]
    )

    return temp_model


# ============================================================
# EXPERIMENT CONFIGURATIONS
# ============================================================

hyperparameter_experiments = [

    # Learning Rate
    {
        "Name": "LR_0.001",
        "Learning Rate": 0.001,
        "Batch Size": 32,
        "Epochs": 10,
        "Optimizer": "Adam",
        "Dense Units": 128,
        "Frozen Layers": "All"
    },

    {
        "Name": "LR_0.0001",
        "Learning Rate": 0.0001,
        "Batch Size": 32,
        "Epochs": 10,
        "Optimizer": "Adam",
        "Dense Units": 128,
        "Frozen Layers": "All"
    },

    # Batch Size
    {
        "Name": "Batch_16",
        "Learning Rate": 0.001,
        "Batch Size": 16,
        "Epochs": 10,
        "Optimizer": "Adam",
        "Dense Units": 128,
        "Frozen Layers": "All"
    },

    {
        "Name": "Batch_32",
        "Learning Rate": 0.001,
        "Batch Size": 32,
        "Epochs": 10,
        "Optimizer": "Adam",
        "Dense Units": 128,
        "Frozen Layers": "All"
    },

    {
        "Name": "Batch_64",
        "Learning Rate": 0.001,
        "Batch Size": 64,
        "Epochs": 10,
        "Optimizer": "Adam",
        "Dense Units": 128,
        "Frozen Layers": "All"
    },

    # Epochs
    {
        "Name": "Epochs_10",
        "Learning Rate": 0.001,
        "Batch Size": 32,
        "Epochs": 10,
        "Optimizer": "Adam",
        "Dense Units": 128,
        "Frozen Layers": "All"
    },

    {
        "Name": "Epochs_20",
        "Learning Rate": 0.001,
        "Batch Size": 32,
        "Epochs": 20,
        "Optimizer": "Adam",
        "Dense Units": 128,
        "Frozen Layers": "All"
    },

    # Optimizer
    {
        "Name": "Adam",
        "Learning Rate": 0.001,
        "Batch Size": 32,
        "Epochs": 10,
        "Optimizer": "Adam",
        "Dense Units": 128,
        "Frozen Layers": "All"
    },

    {
        "Name": "SGD",
        "Learning Rate": 0.001,
        "Batch Size": 32,
        "Epochs": 10,
        "Optimizer": "SGD",
        "Dense Units": 128,
        "Frozen Layers": "All"
    },

    # Dense Units
    {
        "Name": "Dense_128",
        "Learning Rate": 0.001,
        "Batch Size": 32,
        "Epochs": 10,
        "Optimizer": "Adam",
        "Dense Units": 128,
        "Frozen Layers": "All"
    },

    {
        "Name": "Dense_256",
        "Learning Rate": 0.001,
        "Batch Size": 32,
        "Epochs": 10,
        "Optimizer": "Adam",
        "Dense Units": 256,
        "Frozen Layers": "All"
    },

    # Frozen Layers
    {
        "Name": "Frozen_All",
        "Learning Rate": 0.001,
        "Batch Size": 32,
        "Epochs": 10,
        "Optimizer": "Adam",
        "Dense Units": 128,
        "Frozen Layers": "All"
    },

    {
        "Name": "Frozen_Partial",
        "Learning Rate": 0.001,
        "Batch Size": 32,
        "Epochs": 10,
        "Optimizer": "Adam",
        "Dense Units": 128,
        "Frozen Layers": "Partial"
    }
]


# ============================================================
# RUN EXPERIMENTS
# ============================================================

hyperparameter_results = []

for exp in hyperparameter_experiments:

    print("\n" + "=" * 60)
    print("Running:", exp["Name"])
    print("=" * 60)

    temp_model = create_hyperparameter_model(

        learning_rate=exp["Learning Rate"],

        optimizer_name=exp["Optimizer"],

        dense_units=exp["Dense Units"],

        freeze_type=(
            "all"
            if exp["Frozen Layers"] == "All"
            else "partial"
        )
    )

    start = time.time()

    temp_history = temp_model.fit(

        x_train,
        y_train,

        validation_data=(
            x_val,
            y_val
        ),

        epochs=exp["Epochs"],

        batch_size=exp["Batch Size"],

        verbose=1
    )

    elapsed = time.time() - start

    test_loss_temp, test_acc_temp = temp_model.evaluate(
        x_test,
        y_test,
        verbose=0
    )

    hyperparameter_results.append({

        "Experiment": exp["Name"],

        "Learning Rate":
            exp["Learning Rate"],

        "Batch Size":
            exp["Batch Size"],

        "Epochs":
            exp["Epochs"],

        "Optimizer":
            exp["Optimizer"],

        "Dense Units":
            exp["Dense Units"],

        "Frozen Layers":
            exp["Frozen Layers"],

        "Test Accuracy (%)":
            test_acc_temp * 100,

        "Training Time (sec)":
            elapsed,

        "Parameters":
            temp_model.count_params()
    })

    del temp_model

    gc.collect()


# ============================================================
# CREATE RESULTS TABLE
# ============================================================

hyperparameter_df = pd.DataFrame(
    hyperparameter_results
)

print("\n========== HYPERPARAMETER RESULTS ==========")

display(hyperparameter_df)

# ============================================================
# HYPERPARAMETER ACCURACY COMPARISON
# ============================================================

plt.figure(figsize=(14, 6))

plt.bar(
    hyperparameter_df["Experiment"],
    hyperparameter_df["Test Accuracy (%)"]
)

plt.xlabel("Experiment")
plt.ylabel("Test Accuracy (%)")
plt.title("Hyperparameter Study")

plt.xticks(
    rotation=45,
    ha="right"
)

plt.tight_layout()
plt.show()

# ============================================================
# BEST HYPERPARAMETER CONFIGURATION
# ============================================================

best_index = hyperparameter_df[
    "Test Accuracy (%)"
].idxmax()

best_result = hyperparameter_df.loc[
    best_index
]

print("\n========== BEST CONFIGURATION ==========")

print(
    "Experiment:",
    best_result["Experiment"]
)

print(
    "Learning Rate:",
    best_result["Learning Rate"]
)

print(
    "Batch Size:",
    best_result["Batch Size"]
)

print(
    "Epochs:",
    best_result["Epochs"]
)

print(
    "Optimizer:",
    best_result["Optimizer"]
)

print(
    "Dense Units:",
    best_result["Dense Units"]
)

print(
    "Frozen Layers:",
    best_result["Frozen Layers"]
)

print(
    "Test Accuracy:",
    round(
        best_result["Test Accuracy (%)"],
        2
    ),
    "%"
)

# ============================================================
# SECTION 18.1 - PERFORMANCE METRICS TABLE
# ============================================================

final_training_accuracy = (
    fine_history.history["accuracy"][-1]
)

results_18_1 = pd.DataFrame({

    "Metric": [

        "Training Accuracy",

        "Testing Accuracy",

        "Precision",

        "Recall",

        "F1-score",

        "Training Time",

        "Total Parameters"
    ],

    "Value": [

        f"{final_training_accuracy * 100:.2f}%",

        f"{final_accuracy * 100:.2f}%",

        f"{precision:.4f}",

        f"{recall:.4f}",

        f"{f1:.4f}",

        f"{training_time:.2f} seconds",

        f"{model.count_params():,}"
    ]
})

print("========== SECTION 18.1 ==========")

display(results_18_1)

# ============================================================
# LENET-5
# ============================================================

def create_lenet5():

    model = models.Sequential([

        layers.Input(shape=(32, 32, 3)),

        layers.Conv2D(
            6,
            (5, 5),
            activation="tanh",
            padding="same"
        ),

        layers.AveragePooling2D(
            pool_size=(2, 2)
        ),

        layers.Conv2D(
            16,
            (5, 5),
            activation="tanh"
        ),

        layers.AveragePooling2D(
            pool_size=(2, 2)
        ),

        layers.Flatten(),

        layers.Dense(
            120,
            activation="tanh"
        ),

        layers.Dense(
            84,
            activation="tanh"
        ),

        layers.Dense(
            10,
            activation="softmax"
        )
    ])

    model.compile(
        optimizer="adam",
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"]
    )

    return model

# ============================================================
# ALEXNET
# ============================================================

def create_alexnet():

    model = models.Sequential([

        layers.Input(shape=(32, 32, 3)),

        layers.Conv2D(
            96,
            (3, 3),
            padding="same",
            activation="relu"
        ),

        layers.MaxPooling2D(
            pool_size=(2, 2)
        ),

        layers.Conv2D(
            256,
            (3, 3),
            padding="same",
            activation="relu"
        ),

        layers.MaxPooling2D(
            pool_size=(2, 2)
        ),

        layers.Conv2D(
            384,
            (3, 3),
            padding="same",
            activation="relu"
        ),

        layers.Conv2D(
            384,
            (3, 3),
            padding="same",
            activation="relu"
        ),

        layers.Conv2D(
            256,
            (3, 3),
            padding="same",
            activation="relu"
        ),

        layers.MaxPooling2D(
            pool_size=(2, 2)
        ),

        layers.Flatten(),

        layers.Dense(
            4096,
            activation="relu"
        ),

        layers.Dropout(0.5),

        layers.Dense(
            4096,
            activation="relu"
        ),

        layers.Dropout(0.5),

        layers.Dense(
            10,
            activation="softmax"
        )
    ])

    model.compile(
        optimizer="adam",
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"]
    )

    return model

# ============================================================
# VGG16
# ============================================================

from tensorflow.keras.applications import VGG16

def create_vgg16():

    base = VGG16(
        weights="imagenet",
        include_top=False,
        input_shape=(96, 96, 3)
    )

    base.trainable = False

    model = models.Sequential([

        layers.Input(shape=(32, 32, 3)),

        layers.Resizing(
            96,
            96
        ),

        layers.Rescaling(
            2.0,
            offset=-1.0
        ),

        base,

        layers.GlobalAveragePooling2D(),

        layers.Dense(
            128,
            activation="relu"
        ),

        layers.Dense(
            10,
            activation="softmax"
        )
    ])

    model.compile(
        optimizer="adam",
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"]
    )

    return model

# ============================================================
# GOOGLENET / INCEPTION
# ============================================================

def inception_block(
    x,
    filters
):

    f1, f3, f5, fp = filters

    # 1x1 branch
    branch1 = layers.Conv2D(
        f1,
        (1, 1),
        padding="same",
        activation="relu"
    )(x)

    # 3x3 branch
    branch3 = layers.Conv2D(
        f3,
        (1, 1),
        padding="same",
        activation="relu"
    )(x)

    branch3 = layers.Conv2D(
        f3,
        (3, 3),
        padding="same",
        activation="relu"
    )(branch3)

    # 5x5 branch
    branch5 = layers.Conv2D(
        f5,
        (1, 1),
        padding="same",
        activation="relu"
    )(x)

    branch5 = layers.Conv2D(
        f5,
        (5, 5),
        padding="same",
        activation="relu"
    )(branch5)

    # Pooling branch
    branch_pool = layers.MaxPooling2D(
        (3, 3),
        strides=(1, 1),
        padding="same"
    )(x)

    branch_pool = layers.Conv2D(
        fp,
        (1, 1),
        padding="same",
        activation="relu"
    )(branch_pool)

    # Concatenate
    output = layers.Concatenate()([
        branch1,
        branch3,
        branch5,
        branch_pool
    ])

    return output


def create_googlenet():

    inputs = layers.Input(
        shape=(32, 32, 3)
    )

    x = layers.Conv2D(
        64,
        (3, 3),
        padding="same",
        activation="relu"
    )(inputs)

    x = layers.MaxPooling2D(
        (2, 2)
    )(x)

    x = inception_block(
        x,
        (32, 64, 16, 16)
    )

    x = inception_block(
        x,
        (64, 96, 32, 32)
    )

    x = layers.MaxPooling2D(
        (2, 2)
    )(x)

    x = inception_block(
        x,
        (96, 128, 32, 64)
    )

    x = inception_block(
        x,
        (128, 160, 48, 64)
    )

    x = layers.GlobalAveragePooling2D()(x)

    x = layers.Dropout(0.4)(x)

    outputs = layers.Dense(
        10,
        activation="softmax"
    )(x)

    model = models.Model(
        inputs,
        outputs
    )

    model.compile(
        optimizer="adam",
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"]
    )

    return model

# ============================================================
# RESNET50
# ============================================================

from tensorflow.keras.applications import ResNet50

def create_resnet50():

    base = ResNet50(
        weights="imagenet",
        include_top=False,
        input_shape=(96, 96, 3)
    )

    base.trainable = False

    model = models.Sequential([

        layers.Input(shape=(32, 32, 3)),

        layers.Resizing(
            96,
            96
        ),

        layers.Rescaling(
            2.0,
            offset=-1.0
        ),

        base,

        layers.GlobalAveragePooling2D(),

        layers.Dense(
            128,
            activation="relu"
        ),

        layers.Dense(
            10,
            activation="softmax"
        )
    ])

    model.compile(
        optimizer="adam",
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"]
    )

    return model

# ============================================================
# TRAIN AND COMPARE ALL ARCHITECTURES
# ============================================================

architecture_builders = {

    "LeNet-5": create_lenet5,

    "AlexNet": create_alexnet,

    "VGG16": create_vgg16,

    "GoogleNet": create_googlenet,

    "ResNet50": create_resnet50
}


architecture_results = []

ARCH_EPOCHS = 10
ARCH_BATCH_SIZE = 32


for architecture_name, builder in architecture_builders.items():

    print("\n")
    print("=" * 70)
    print("TRAINING:", architecture_name)
    print("=" * 70)

    # Create model
    architecture_model = builder()

    # Show parameter count
    parameter_count = (
        architecture_model.count_params()
    )

    print(
        "Total Parameters:",
        f"{parameter_count:,}"
    )

    # Start timer
    start = time.time()

    # Train
    architecture_history = architecture_model.fit(

        x_train,
        y_train,

        validation_data=(
            x_val,
            y_val
        ),

        epochs=ARCH_EPOCHS,

        batch_size=ARCH_BATCH_SIZE,

        verbose=1
    )

    # Training time
    architecture_training_time = (
        time.time() - start
    )

    # Test
    architecture_loss, architecture_accuracy = (
        architecture_model.evaluate(
            x_test,
            y_test,
            batch_size=ARCH_BATCH_SIZE,
            verbose=0
        )
    )

    # Save result
    architecture_results.append({

        "Model":
            architecture_name,

        "Parameters":
            parameter_count,

        "Accuracy (%)":
            architecture_accuracy * 100,

        "Training Time (sec)":
            architecture_training_time
    })

    print(
        "\n",
        architecture_name,
        "Accuracy:",
        round(
            architecture_accuracy * 100,
            2
        ),
        "%"
    )

    print(
        architecture_name,
        "Training Time:",
        round(
            architecture_training_time,
            2
        ),
        "seconds"
    )

    # Delete model before next architecture
    del architecture_model

    gc.collect()


# ============================================================
# CREATE COMPARISON TABLE
# ============================================================

architecture_df = pd.DataFrame(
    architecture_results
)

architecture_df["Parameters"] = (
    architecture_df["Parameters"].map(
        lambda x: f"{x:,}"
    )
)

architecture_df["Accuracy (%)"] = (
    architecture_df["Accuracy (%)"].round(2)
)

architecture_df["Training Time (sec)"] = (
    architecture_df["Training Time (sec)"].round(2)
)

print("\n")
print("========== SECTION 18.2 ==========")

display(architecture_df)

# ============================================================
# ARCHITECTURE ACCURACY COMPARISON
# ============================================================

# Convert back to numeric
plot_df = pd.DataFrame(
    architecture_results
)

plt.figure(figsize=(10, 6))

plt.bar(
    plot_df["Model"],
    plot_df["Accuracy (%)"]
)

plt.xlabel("CNN Architecture")
plt.ylabel("Accuracy (%)")
plt.title(
    "Comparison of CNN Architectures"
)

plt.xticks(rotation=20)

plt.tight_layout()

plt.show()

# ============================================================
# ARCHITECTURE TRAINING TIME COMPARISON
# ============================================================

plt.figure(figsize=(10, 6))

plt.bar(
    plot_df["Model"],
    plot_df["Training Time (sec)"]
)

plt.xlabel("CNN Architecture")
plt.ylabel("Training Time (seconds)")
plt.title(
    "Training Time Comparison of CNN Architectures"
)

plt.xticks(rotation=20)

plt.tight_layout()

plt.show()

